### ISSUE TITLE
Support for memoization of rules (rules that always return the same generated value)

### ISSUE THREAD

**Issue by maetl** [maetl/calyx#4] opened 2016-02-09 12:58 UTC
An alternative to #3 is to add explicit memoization support to the API. Haven’t scoped out what this might mean yet, but here’s a sketch.

Can already do this now at the global level by injecting single values into the rule config:

```ruby
rule :protagonist, ['Vladimir', 'Estragon'].sample
```

This pattern could be encoded by default with a `memo` helper method:

```ruby
memo :protagonist, 'Vladimir', 'Estragon'
```

Alternative is to support a special memoization substitution syntax:

```ruby
rule :protagonist_name, 'Vladimir', 'Estragon'
rule :protagonist, '{{protagonist_name}}'
```

```ruby
rule :protagonist_name, 'Vladimir', 'Estragon'
rule :protagonist, '{@protagonist_name}'
```

```ruby
rule :protagonist_name, 'Vladimir', 'Estragon'
rule :protagonist, '{&protagonist_name}'
```

```ruby
rule :protagonist_name, 'Vladimir', 'Estragon'
rule :protagonist, '{protagonist_name!}'
```

**Comment by tra38** [comment] 2016-02-15 03:05
I wrote some code to try and resolve the issue and this is what I come up with on my local branch:
```ruby
      def memo(name, *productions, &production)
        memoized_value = productions.sample
        registry.rule(name, memoized_value)
      end

This seems to work fine but the problem is that this approach seems to be occurring on the global level; once I run memo, then the memoized value will be fixed for all instances of the Calyx class. It may seem more sensible to delay "productions.sample" until when you actually initialize the class in question (though this could be me overopitiziming and I should probably consider avoiding this feature because YAGNI). Maybe I should look at the registry module some more and see what can be done to coerce it to do some memoization.

**Comment by maetl** [comment] 2016-02-15 11:12
Yeah, these sorts of problems are going to come up again and again with the API based on class methods. Sticking things onto the base class is another form of global state in a way.

>  It may seem more sensible to delay "productions.sample" until when you actually initialize the class in question

I actually think this is a good idea. Would require some sort of currying or lazy evaluation. Taking your example above, `registry.rule(name, memoized_value)` — the memoized value here needs to be a callable proc or something, so that it only evaluates `productions.sample` when it is first used in an instance, rather than at grammar construction time.

I just realised that the use case I described above (which I was solving in my NaNoGenMo project by injecting variables—`rule :protagonist, ['Vladimir', 'Estragon'].sample`) is actually a different requirement. From the grammar perspective this ends up being the same as a hard coded string, and so __should__ be fixed for all instances of the Calyx class.

**Comment by tra38** [comment] 2016-02-16 13:52
I did delay productions.sample until actual initialization, but it doesn't actually seem to help (the same value keeps appearing...and the proc, when called, simply creates a Grammar::Production::Terminal with the same 'atom').

I think I may be better off just writing out a template context map instead of trying to worry about this issue. Surely, we can write a memo function, but it's probably too buggy and confusing to be relied on. A template complex map seems more sensible and reusable.

**Comment by maetl** [comment] 2016-04-13 13:02
I’ve released experimental support for this feature in `0.9.1`.

Any production rule (right hand side only) can be memoized by appending `@` to the symbol or template string. This provides a simple and effective way of consistently referring to the same generated value in different places and will hopefully be useful for simplifying larger and more complex generators.

Use with symbol (this is kind of the equivalent to setting a ‘global variable’ in the grammar):

```ruby
grammar = Calyx::Grammar.new do
  rule :start, "Enter {character}. Exit {character}."
  rule :character, :@name
  rule :name, "Vladimir", "Estragon"
end
```

Use with template interpolation:

```ruby
grammar = Calyx::Grammar.new do
  rule :burger, "Monolith {@extras}"
  rule :burger_combo, "Jumbo Monolith {@extras}"
  rule :extras, "w/ extra grease", "w/ polycheese"
end
```

**Closed** 2016-06-28 12:15 UTC
